# Test4 - Data structure library generated by CANDataStructureGenerator.
###########################################################################
# Try to find Test4 library.
# The user can specify an additional search path using the CMake variable
# TEST4_DIR
# First, search at the specific user path setting.
IF(NOT ("${TEST4_DIR}" STREQUAL ""))
    FIND_PATH(TEST4_INCLUDE_DIR test4/GeneratedHeaders_Test4.h
                 NAMES test4
                 PATHS ${TEST4_DIR}/include
                 NO_DEFAULT_PATH)
    FIND_LIBRARY(TEST4_LIBRARY
                 NAMES test4 test4-static
                 PATHS ${TEST4_DIR}/lib
                 NO_DEFAULT_PATH)
ENDIF()
IF(   ("${TEST4_INCLUDE_DIR}" STREQUAL "TEST4_INCLUDE_DIR-NOTFOUND")
   OR ("${TEST4_DIR}" STREQUAL "") )
    MESSAGE(STATUS "Trying to find Test4 in default paths.")
    # If not found, use the system's search paths.
    FIND_PATH(TEST4_INCLUDE_DIR test4/GeneratedHeaders_Test4.h
                 NAMES test4
                 PATHS /usr/include
                       /usr/local/include)
    FIND_LIBRARY(TEST4_LIBRARY
                 NAMES test4 test4-static
                 PATHS /usr/lib
                       /usr/lib64
                       /usr/local/lib
                       /usr/local/lib64)
ENDIF()
IF("${TEST4_INCLUDE_DIR}" STREQUAL "")
    MESSAGE(FATAL_ERROR "Could not find Test4 library.")
ENDIF()
###########################################################################
# Set linking libraries.
SET(TEST4_LIBRARIES ${TEST4_LIBRARY})
SET(TEST4_INCLUDE_DIRS ${TEST4_INCLUDE_DIR})
###########################################################################
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibTest4 DEFAULT_MSG
                                  TEST4_LIBRARY TEST4_INCLUDE_DIR)
MARK_AS_ADVANCED(TEST4_INCLUDE_DIR TEST4_LIBRARY)
