# Test19 - Data structure library generated by CANDataStructureGenerator.
###########################################################################
# Try to find Test19 library.
# The user can specify an additional search path using the CMake variable
# TEST19_DIR
# First, search at the specific user path setting.
IF(NOT ("${TEST19_DIR}" STREQUAL ""))
    FIND_PATH(TEST19_INCLUDE_DIR test19/GeneratedHeaders_Test19.h
                 NAMES test19
                 PATHS ${TEST19_DIR}/include
                 NO_DEFAULT_PATH)
    FIND_LIBRARY(TEST19_LIBRARY
                 NAMES test19 test19-static
                 PATHS ${TEST19_DIR}/lib
                 NO_DEFAULT_PATH)
ENDIF()
IF(   ("${TEST19_INCLUDE_DIR}" STREQUAL "TEST19_INCLUDE_DIR-NOTFOUND")
   OR ("${TEST19_DIR}" STREQUAL "") )
    MESSAGE(STATUS "Trying to find Test19 in default paths.")
    # If not found, use the system's search paths.
    FIND_PATH(TEST19_INCLUDE_DIR test19/GeneratedHeaders_Test19.h
                 NAMES test19
                 PATHS /usr/include
                       /usr/local/include)
    FIND_LIBRARY(TEST19_LIBRARY
                 NAMES test19 test19-static
                 PATHS /usr/lib
                       /usr/lib64
                       /usr/local/lib
                       /usr/local/lib64)
ENDIF()
IF("${TEST19_INCLUDE_DIR}" STREQUAL "")
    MESSAGE(FATAL_ERROR "Could not find Test19 library.")
ENDIF()
###########################################################################
# Set linking libraries.
SET(TEST19_LIBRARIES ${TEST19_LIBRARY})
SET(TEST19_INCLUDE_DIRS ${TEST19_INCLUDE_DIR})
###########################################################################
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibTest19 DEFAULT_MSG
                                  TEST19_LIBRARY TEST19_INCLUDE_DIR)
MARK_AS_ADVANCED(TEST19_INCLUDE_DIR TEST19_LIBRARY)
