/*
 * THIS IS A GENERATED FILE - CHANGES WILL BE OVERWRITTEN.
 */

#ifndef GENERATEDHEADERS_TEST15_H
#define GENERATEDHEADERS_TEST15_H

#include "test15/generated/Test15Simple.h"

#endif //GENERATEDHEADERS_TEST15_H
