/*
 * THIS IS A GENERATED FILE - CHANGES WILL BE OVERWRITTEN.
 */

#ifndef GENERATEDHEADERS_TEST3_H
#define GENERATEDHEADERS_TEST3_H

#include "test3/generated/Test3.h"

#endif //GENERATEDHEADERS_TEST3_H
