# Test12 - Data structure library generated by CANDataStructureGenerator.
###########################################################################
# Try to find Test12 library.
# The user can specify an additional search path using the CMake variable
# TEST12_DIR
# First, search at the specific user path setting.
IF(NOT ("${TEST12_DIR}" STREQUAL ""))
    FIND_PATH(TEST12_INCLUDE_DIR test12/GeneratedHeaders_Test12.h
                 NAMES test12
                 PATHS ${TEST12_DIR}/include
                 NO_DEFAULT_PATH)
    FIND_LIBRARY(TEST12_LIBRARY
                 NAMES test12 test12-static
                 PATHS ${TEST12_DIR}/lib
                 NO_DEFAULT_PATH)
ENDIF()
IF(   ("${TEST12_INCLUDE_DIR}" STREQUAL "TEST12_INCLUDE_DIR-NOTFOUND")
   OR ("${TEST12_DIR}" STREQUAL "") )
    MESSAGE(STATUS "Trying to find Test12 in default paths.")
    # If not found, use the system's search paths.
    FIND_PATH(TEST12_INCLUDE_DIR test12/GeneratedHeaders_Test12.h
                 NAMES test12
                 PATHS /usr/include
                       /usr/local/include)
    FIND_LIBRARY(TEST12_LIBRARY
                 NAMES test12 test12-static
                 PATHS /usr/lib
                       /usr/lib64
                       /usr/local/lib
                       /usr/local/lib64)
ENDIF()
IF("${TEST12_INCLUDE_DIR}" STREQUAL "")
    MESSAGE(FATAL_ERROR "Could not find Test12 library.")
ENDIF()
###########################################################################
# Set linking libraries.
SET(TEST12_LIBRARIES ${TEST12_LIBRARY})
SET(TEST12_INCLUDE_DIRS ${TEST12_INCLUDE_DIR})
###########################################################################
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibTest12 DEFAULT_MSG
                                  TEST12_LIBRARY TEST12_INCLUDE_DIR)
MARK_AS_ADVANCED(TEST12_INCLUDE_DIR TEST12_LIBRARY)
