# Test18 - Data structure library generated by DataStructureGenerator.
###########################################################################
# Try to find Test18 library.
# The user can specify an additional search path using the CMake variable
# TEST18_DIR
# First, search at the specific user path setting.
IF(NOT ("${TEST18_DIR}" STREQUAL ""))
    FIND_PATH(TEST18_INCLUDE_DIR test18/GeneratedHeaders_Test18.h
                 NAMES test18
                 PATHS ${TEST18_DIR}/include
                 NO_DEFAULT_PATH)
    FIND_LIBRARY(TEST18_LIBRARY
                 NAMES test18 test18-static
                 PATHS ${TEST18_DIR}/lib
                 NO_DEFAULT_PATH)
ENDIF()
IF(   ("${TEST18_INCLUDE_DIR}" STREQUAL "TEST18_INCLUDE_DIR-NOTFOUND")
   OR ("${TEST18_DIR}" STREQUAL "") )
    MESSAGE(STATUS "Trying to find Test18 in default paths.")
    # If not found, use the system's search paths.
    FIND_PATH(TEST18_INCLUDE_DIR test18/GeneratedHeaders_Test18.h
                 NAMES test18
                 PATHS /usr/include
                       /usr/local/include)
    FIND_LIBRARY(TEST18_LIBRARY
                 NAMES test18 test18-static
                 PATHS /usr/lib
                       /usr/lib64
                       /usr/local/lib
                       /usr/local/lib64)
ENDIF()
IF("${TEST18_INCLUDE_DIR}" STREQUAL "")
    MESSAGE(FATAL_ERROR "Could not find Test18 library.")
ENDIF()
###########################################################################
# Set linking libraries.
SET(TEST18_LIBRARIES ${TEST18_LIBRARY})
SET(TEST18_INCLUDE_DIRS ${TEST18_INCLUDE_DIR})
###########################################################################
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibTest18 DEFAULT_MSG
                                  TEST18_LIBRARY TEST18_INCLUDE_DIR)
MARK_AS_ADVANCED(TEST18_INCLUDE_DIR TEST18_LIBRARY)
