# Test7 - Data structure library generated by CANDataStructureGenerator.
###########################################################################
# Try to find Test7 library.
# The user can specify an additional search path using the CMake variable
# TEST7_DIR
# First, search at the specific user path setting.
IF(NOT ("${TEST7_DIR}" STREQUAL ""))
    FIND_PATH(TEST7_INCLUDE_DIR test7/GeneratedHeaders_Test7.h
                 NAMES test7
                 PATHS ${TEST7_DIR}/include
                 NO_DEFAULT_PATH)
    FIND_LIBRARY(TEST7_LIBRARY
                 NAMES test7 test7-static
                 PATHS ${TEST7_DIR}/lib
                 NO_DEFAULT_PATH)
ENDIF()
IF(   ("${TEST7_INCLUDE_DIR}" STREQUAL "TEST7_INCLUDE_DIR-NOTFOUND")
   OR ("${TEST7_DIR}" STREQUAL "") )
    MESSAGE(STATUS "Trying to find Test7 in default paths.")
    # If not found, use the system's search paths.
    FIND_PATH(TEST7_INCLUDE_DIR test7/GeneratedHeaders_Test7.h
                 NAMES test7
                 PATHS /usr/include
                       /usr/local/include)
    FIND_LIBRARY(TEST7_LIBRARY
                 NAMES test7 test7-static
                 PATHS /usr/lib
                       /usr/lib64
                       /usr/local/lib
                       /usr/local/lib64)
ENDIF()
IF("${TEST7_INCLUDE_DIR}" STREQUAL "")
    MESSAGE(FATAL_ERROR "Could not find Test7 library.")
ENDIF()
###########################################################################
# Set linking libraries.
SET(TEST7_LIBRARIES ${TEST7_LIBRARY})
SET(TEST7_INCLUDE_DIRS ${TEST7_INCLUDE_DIR})
###########################################################################
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibTest7 DEFAULT_MSG
                                  TEST7_LIBRARY TEST7_INCLUDE_DIR)
MARK_AS_ADVANCED(TEST7_INCLUDE_DIR TEST7_LIBRARY)
