/*
 * THIS IS A GENERATED FILE - CHANGES WILL BE OVERWRITTEN.
 */

#ifndef GENERATEDHEADERS_TEST4_H
#define GENERATEDHEADERS_TEST4_H

#include "test4/generated/Test4.h"

#endif //GENERATEDHEADERS_TEST4_H
