# Test14 - Data structure library generated by CANDataStructureGenerator.
###########################################################################
# Try to find Test14 library.
# The user can specify an additional search path using the CMake variable
# TEST14_DIR
# First, search at the specific user path setting.
IF(NOT ("${TEST14_DIR}" STREQUAL ""))
    FIND_PATH(TEST14_INCLUDE_DIR test14/GeneratedHeaders_Test14.h
                 NAMES test14
                 PATHS ${TEST14_DIR}/include
                 NO_DEFAULT_PATH)
    FIND_LIBRARY(TEST14_LIBRARY
                 NAMES test14 test14-static
                 PATHS ${TEST14_DIR}/lib
                 NO_DEFAULT_PATH)
ENDIF()
IF(   ("${TEST14_INCLUDE_DIR}" STREQUAL "TEST14_INCLUDE_DIR-NOTFOUND")
   OR ("${TEST14_DIR}" STREQUAL "") )
    MESSAGE(STATUS "Trying to find Test14 in default paths.")
    # If not found, use the system's search paths.
    FIND_PATH(TEST14_INCLUDE_DIR test14/GeneratedHeaders_Test14.h
                 NAMES test14
                 PATHS /usr/include
                       /usr/local/include)
    FIND_LIBRARY(TEST14_LIBRARY
                 NAMES test14 test14-static
                 PATHS /usr/lib
                       /usr/lib64
                       /usr/local/lib
                       /usr/local/lib64)
ENDIF()
IF("${TEST14_INCLUDE_DIR}" STREQUAL "")
    MESSAGE(FATAL_ERROR "Could not find Test14 library.")
ENDIF()
###########################################################################
# Set linking libraries.
SET(TEST14_LIBRARIES ${TEST14_LIBRARY})
SET(TEST14_INCLUDE_DIRS ${TEST14_INCLUDE_DIR})
###########################################################################
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibTest14 DEFAULT_MSG
                                  TEST14_LIBRARY TEST14_INCLUDE_DIR)
MARK_AS_ADVANCED(TEST14_INCLUDE_DIR TEST14_LIBRARY)
