# Test11 - Data structure library generated by CANDataStructureGenerator.
###########################################################################
# Try to find Test11 library.
# The user can specify an additional search path using the CMake variable
# TEST11_DIR
# First, search at the specific user path setting.
IF(NOT ("${TEST11_DIR}" STREQUAL ""))
    FIND_PATH(TEST11_INCLUDE_DIR test11/GeneratedHeaders_Test11.h
                 NAMES test11
                 PATHS ${TEST11_DIR}/include
                 NO_DEFAULT_PATH)
    FIND_LIBRARY(TEST11_LIBRARY
                 NAMES test11 test11-static
                 PATHS ${TEST11_DIR}/lib
                 NO_DEFAULT_PATH)
ENDIF()
IF(   ("${TEST11_INCLUDE_DIR}" STREQUAL "TEST11_INCLUDE_DIR-NOTFOUND")
   OR ("${TEST11_DIR}" STREQUAL "") )
    MESSAGE(STATUS "Trying to find Test11 in default paths.")
    # If not found, use the system's search paths.
    FIND_PATH(TEST11_INCLUDE_DIR test11/GeneratedHeaders_Test11.h
                 NAMES test11
                 PATHS /usr/include
                       /usr/local/include)
    FIND_LIBRARY(TEST11_LIBRARY
                 NAMES test11 test11-static
                 PATHS /usr/lib
                       /usr/lib64
                       /usr/local/lib
                       /usr/local/lib64)
ENDIF()
IF("${TEST11_INCLUDE_DIR}" STREQUAL "")
    MESSAGE(FATAL_ERROR "Could not find Test11 library.")
ENDIF()
###########################################################################
# Set linking libraries.
SET(TEST11_LIBRARIES ${TEST11_LIBRARY})
SET(TEST11_INCLUDE_DIRS ${TEST11_INCLUDE_DIR})
###########################################################################
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibTest11 DEFAULT_MSG
                                  TEST11_LIBRARY TEST11_INCLUDE_DIR)
MARK_AS_ADVANCED(TEST11_INCLUDE_DIR TEST11_LIBRARY)
