# Test6 - Data structure library generated by DataStructureGenerator.
###########################################################################
# Try to find Test6 library.
# The user can specify an additional search path using the CMake variable
# TEST6_DIR
# First, search at the specific user path setting.
IF(NOT ("${TEST6_DIR}" STREQUAL ""))
    FIND_PATH(TEST6_INCLUDE_DIR test6/GeneratedHeaders_Test6.h
                 NAMES test6
                 PATHS ${TEST6_DIR}/include
                 NO_DEFAULT_PATH)
    FIND_LIBRARY(TEST6_LIBRARY
                 NAMES test6 test6-static
                 PATHS ${TEST6_DIR}/lib
                 NO_DEFAULT_PATH)
ENDIF()
IF(   ("${TEST6_INCLUDE_DIR}" STREQUAL "TEST6_INCLUDE_DIR-NOTFOUND")
   OR ("${TEST6_DIR}" STREQUAL "") )
    MESSAGE(STATUS "Trying to find Test6 in default paths.")
    # If not found, use the system's search paths.
    FIND_PATH(TEST6_INCLUDE_DIR test6/GeneratedHeaders_Test6.h
                 NAMES test6
                 PATHS /usr/include
                       /usr/local/include)
    FIND_LIBRARY(TEST6_LIBRARY
                 NAMES test6 test6-static
                 PATHS /usr/lib
                       /usr/lib64
                       /usr/local/lib
                       /usr/local/lib64)
ENDIF()
IF("${TEST6_INCLUDE_DIR}" STREQUAL "")
    MESSAGE(FATAL_ERROR "Could not find Test6 library.")
ENDIF()
###########################################################################
# Set linking libraries.
SET(TEST6_LIBRARIES ${TEST6_LIBRARY})
SET(TEST6_INCLUDE_DIRS ${TEST6_INCLUDE_DIR})
###########################################################################
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibTest6 DEFAULT_MSG
                                  TEST6_LIBRARY TEST6_INCLUDE_DIR)
MARK_AS_ADVANCED(TEST6_INCLUDE_DIR TEST6_LIBRARY)
