.\" Manpage for odlivefeed
.\" Author: Christian Berger <christian.berger@gu.se>.

.TH odlivefeed 1 "19 June 2017" "4.13.0" "odlivefeed man page"

.SH NAME
odlivefeed \- This tool prints content from containers exchanged in an OpenDaVINCI container conference session to stdout in a user-readable representation using the ncurses library.



.SH SYNOPSIS
.B odlivefeed --cid=<CID> [OPTIONS]



.SH DESCRIPTION
odlivefeed belongs to OpenDaVINCI and is a tool to print the content of containers from an
OpenDaVINCI container conference session to stdout in a user-readable representation.

This tool can only be used within an existing OpenDaVINCI container conference session
created by odsupercomponent(1).



.SH OPTIONS
.B --cid=<CID>
.RS
This parameter specifies the conference identifier (CID) that is used to join a
running container conference session. The session itself needs to be created by
odsupercomponent(1).
.RE


.SH EXAMPLES
The following command printing the content to stdout from odsupercomponent's session 111.

.B odlivefeed --cid=111



.SH SEE ALSO
odfilter(1), odlivefeed(1), odplayer(1), odplayerh264(1), odrecinspect(1), odrecorder(1), odrecorderh264(1), odredirector(1), odsplit(1)


.SH BUGS
No known bugs.



.SH AUTHOR
Christian Berger (christian.berger@gu.se)

