/*
* generated by Xtext
*/
package org.opendavinci;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class DataModelStandaloneSetup extends DataModelStandaloneSetupGenerated{

	public static void doSetup() {
		new DataModelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

