# Test20 - Data structure library generated by CANDataStructureGenerator.
###########################################################################
# Try to find Test20 library.
# The user can specify an additional search path using the CMake variable
# TEST20_DIR
# First, search at the specific user path setting.
IF(NOT ("${TEST20_DIR}" STREQUAL ""))
    FIND_PATH(TEST20_INCLUDE_DIR test20/GeneratedHeaders_Test20.h
                 NAMES test20
                 PATHS ${TEST20_DIR}/include
                 NO_DEFAULT_PATH)
    FIND_LIBRARY(TEST20_LIBRARY
                 NAMES test20 test20-static
                 PATHS ${TEST20_DIR}/lib
                 NO_DEFAULT_PATH)
ENDIF()
IF(   ("${TEST20_INCLUDE_DIR}" STREQUAL "TEST20_INCLUDE_DIR-NOTFOUND")
   OR ("${TEST20_DIR}" STREQUAL "") )
    MESSAGE(STATUS "Trying to find Test20 in default paths.")
    # If not found, use the system's search paths.
    FIND_PATH(TEST20_INCLUDE_DIR test20/GeneratedHeaders_Test20.h
                 NAMES test20
                 PATHS /usr/include
                       /usr/local/include)
    FIND_LIBRARY(TEST20_LIBRARY
                 NAMES test20 test20-static
                 PATHS /usr/lib
                       /usr/lib64
                       /usr/local/lib
                       /usr/local/lib64)
ENDIF()
IF("${TEST20_INCLUDE_DIR}" STREQUAL "")
    MESSAGE(FATAL_ERROR "Could not find Test20 library.")
ENDIF()
###########################################################################
# Set linking libraries.
SET(TEST20_LIBRARIES ${TEST20_LIBRARY})
SET(TEST20_INCLUDE_DIRS ${TEST20_INCLUDE_DIR})
###########################################################################
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibTest20 DEFAULT_MSG
                                  TEST20_LIBRARY TEST20_INCLUDE_DIR)
MARK_AS_ADVANCED(TEST20_INCLUDE_DIR TEST20_LIBRARY)
