# Test8 - Data structure library generated by DataStructureGenerator.
###########################################################################
# Try to find Test8 library.
# The user can specify an additional search path using the CMake variable
# TEST8_DIR
# First, search at the specific user path setting.
IF(NOT ("${TEST8_DIR}" STREQUAL ""))
    FIND_PATH(TEST8_INCLUDE_DIR test8/GeneratedHeaders_Test8.h
                 NAMES test8
                 PATHS ${TEST8_DIR}/include
                 NO_DEFAULT_PATH)
    FIND_LIBRARY(TEST8_LIBRARY
                 NAMES test8 test8-static
                 PATHS ${TEST8_DIR}/lib
                 NO_DEFAULT_PATH)
ENDIF()
IF(   ("${TEST8_INCLUDE_DIR}" STREQUAL "TEST8_INCLUDE_DIR-NOTFOUND")
   OR ("${TEST8_DIR}" STREQUAL "") )
    MESSAGE(STATUS "Trying to find Test8 in default paths.")
    # If not found, use the system's search paths.
    FIND_PATH(TEST8_INCLUDE_DIR test8/GeneratedHeaders_Test8.h
                 NAMES test8
                 PATHS /usr/include
                       /usr/local/include)
    FIND_LIBRARY(TEST8_LIBRARY
                 NAMES test8 test8-static
                 PATHS /usr/lib
                       /usr/lib64
                       /usr/local/lib
                       /usr/local/lib64)
ENDIF()
IF("${TEST8_INCLUDE_DIR}" STREQUAL "")
    MESSAGE(FATAL_ERROR "Could not find Test8 library.")
ENDIF()
###########################################################################
# Set linking libraries.
SET(TEST8_LIBRARIES ${TEST8_LIBRARY})
SET(TEST8_INCLUDE_DIRS ${TEST8_INCLUDE_DIR})
###########################################################################
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibTest8 DEFAULT_MSG
                                  TEST8_LIBRARY TEST8_INCLUDE_DIR)
MARK_AS_ADVANCED(TEST8_INCLUDE_DIR TEST8_LIBRARY)
