/*
 * THIS IS A GENERATED FILE - CHANGES WILL BE OVERWRITTEN.
 */

#ifndef GENERATEDHEADERS_TEST18_H
#define GENERATEDHEADERS_TEST18_H

#include "test18/generated/Test18.h"

#endif //GENERATEDHEADERS_TEST18_H
