/*
* generated by Xtext
*/
package org.opendavinci;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class CANDataModelStandaloneSetup extends CANDataModelStandaloneSetupGenerated{

	public static void doSetup() {
		new CANDataModelStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

