# Test16 - Data structure library generated by CANDataStructureGenerator.
###########################################################################
# Try to find Test16 library.
# The user can specify an additional search path using the CMake variable
# TEST16_DIR
# First, search at the specific user path setting.
IF(NOT ("${TEST16_DIR}" STREQUAL ""))
    FIND_PATH(TEST16_INCLUDE_DIR test16/GeneratedHeaders_Test16.h
                 NAMES test16
                 PATHS ${TEST16_DIR}/include
                 NO_DEFAULT_PATH)
    FIND_LIBRARY(TEST16_LIBRARY
                 NAMES test16 test16-static
                 PATHS ${TEST16_DIR}/lib
                 NO_DEFAULT_PATH)
ENDIF()
IF(   ("${TEST16_INCLUDE_DIR}" STREQUAL "TEST16_INCLUDE_DIR-NOTFOUND")
   OR ("${TEST16_DIR}" STREQUAL "") )
    MESSAGE(STATUS "Trying to find Test16 in default paths.")
    # If not found, use the system's search paths.
    FIND_PATH(TEST16_INCLUDE_DIR test16/GeneratedHeaders_Test16.h
                 NAMES test16
                 PATHS /usr/include
                       /usr/local/include)
    FIND_LIBRARY(TEST16_LIBRARY
                 NAMES test16 test16-static
                 PATHS /usr/lib
                       /usr/lib64
                       /usr/local/lib
                       /usr/local/lib64)
ENDIF()
IF("${TEST16_INCLUDE_DIR}" STREQUAL "")
    MESSAGE(FATAL_ERROR "Could not find Test16 library.")
ENDIF()
###########################################################################
# Set linking libraries.
SET(TEST16_LIBRARIES ${TEST16_LIBRARY})
SET(TEST16_INCLUDE_DIRS ${TEST16_INCLUDE_DIR})
###########################################################################
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibTest16 DEFAULT_MSG
                                  TEST16_LIBRARY TEST16_INCLUDE_DIR)
MARK_AS_ADVANCED(TEST16_INCLUDE_DIR TEST16_LIBRARY)
