# Test10 - Data structure library generated by DataStructureGenerator.
###########################################################################
# Try to find Test10 library.
# The user can specify an additional search path using the CMake variable
# TEST10_DIR
# First, search at the specific user path setting.
IF(NOT ("${TEST10_DIR}" STREQUAL ""))
    FIND_PATH(TEST10_INCLUDE_DIR test10/GeneratedHeaders_Test10.h
                 NAMES test10
                 PATHS ${TEST10_DIR}/include
                 NO_DEFAULT_PATH)
    FIND_LIBRARY(TEST10_LIBRARY
                 NAMES test10 test10-static
                 PATHS ${TEST10_DIR}/lib
                 NO_DEFAULT_PATH)
ENDIF()
IF(   ("${TEST10_INCLUDE_DIR}" STREQUAL "TEST10_INCLUDE_DIR-NOTFOUND")
   OR ("${TEST10_DIR}" STREQUAL "") )
    MESSAGE(STATUS "Trying to find Test10 in default paths.")
    # If not found, use the system's search paths.
    FIND_PATH(TEST10_INCLUDE_DIR test10/GeneratedHeaders_Test10.h
                 NAMES test10
                 PATHS /usr/include
                       /usr/local/include)
    FIND_LIBRARY(TEST10_LIBRARY
                 NAMES test10 test10-static
                 PATHS /usr/lib
                       /usr/lib64
                       /usr/local/lib
                       /usr/local/lib64)
ENDIF()
IF("${TEST10_INCLUDE_DIR}" STREQUAL "")
    MESSAGE(FATAL_ERROR "Could not find Test10 library.")
ENDIF()
###########################################################################
# Set linking libraries.
SET(TEST10_LIBRARIES ${TEST10_LIBRARY})
SET(TEST10_INCLUDE_DIRS ${TEST10_INCLUDE_DIR})
###########################################################################
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibTest10 DEFAULT_MSG
                                  TEST10_LIBRARY TEST10_INCLUDE_DIR)
MARK_AS_ADVANCED(TEST10_INCLUDE_DIR TEST10_LIBRARY)
