# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: OpenDaVINCITestData.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='OpenDaVINCITestData.proto',
  package='odcore.testdata',
  syntax='proto2',
  serialized_pb=_b('\n\x19OpenDaVINCITestData.proto\x12\x0fodcore.testdata\"\x1d\n\x0cTestMessage1\x12\r\n\x01\x61\x18\x01 \x01(\r:\x02\x31\x32\".\n\x0cTestMessage2\x12\x0e\n\x06\x66ield1\x18\x01 \x01(\r\x12\x0e\n\x06\x66ield2\x18\x02 \x01(\x11\"\x1e\n\x0cTestMessage3\x12\x0e\n\x06\x66ield1\x18\x02 \x01(\t\"=\n\x0cTestMessage4\x12-\n\x06\x66ield1\x18\x03 \x01(\x0b\x32\x1d.odcore.testdata.TestMessage1\"\xc1\x02\n\x0cTestMessage5\x12\x11\n\x06\x66ield1\x18\x01 \x01(\r:\x01\x31\x12\x12\n\x06\x66ield2\x18\x02 \x01(\x11:\x02-1\x12\x13\n\x06\x66ield3\x18\x03 \x01(\r:\x03\x31\x30\x30\x12\x14\n\x06\x66ield4\x18\x04 \x01(\x11:\x04-100\x12\x15\n\x06\x66ield5\x18\x05 \x01(\r:\x05\x31\x30\x30\x30\x30\x12\x16\n\x06\x66ield6\x18\x06 \x01(\x11:\x06-10000\x12\x15\n\x06\x66ield7\x18\x07 \x01(\x04:\x05\x31\x32\x33\x34\x35\x12\x16\n\x06\x66ield8\x18\x08 \x01(\x12:\x06-12345\x12\x17\n\x06\x66ield9\x18\t \x01(\x02:\x07-1.2345\x12\x19\n\x07\x66ield10\x18\n \x01(\x01:\x08-10.2345\x12\x1d\n\x07\x66ield11\x18\x0b \x01(\t:\x0cHello World!\x12.\n\x07\x66ield12\x18\x0c \x01(\x0b\x32\x1d.odcore.testdata.TestMessage1\"\"\n\x0cTestMessage6\x12\x12\n\x06\x66ield1\x18\x04 \x03(\rB\x02\x10\x01\"\"\n\x0cTestMessage7\x12\x12\n\x06\x66ield1\x18\x01 \x03(\x02\x42\x02\x10\x01\"/\n\x11TestMessage8Entry\x12\x0b\n\x03key\x18\x01 \x01(\r\x12\r\n\x05value\x18\x02 \x01(\r\"B\n\x0cTestMessage8\x12\x32\n\x06\x66ield1\x18\x01 \x03(\x0b\x32\".odcore.testdata.TestMessage8Entry\";\n\rTestMessage10\x12\x14\n\x08myArray1\x18\x01 \x03(\rB\x02\x10\x01\x12\x14\n\x08myArray2\x18\x02 \x03(\x02\x42\x02\x10\x01\"2\n\tTimeStamp\x12\x0f\n\x07seconds\x18\x01 \x01(\x11\x12\x14\n\x0cmicroseconds\x18\x02 \x01(\x11\"\x8d\x01\n\tContainer\x12\x10\n\x08\x64\x61taType\x18\x01 \x01(\x11\x12\x16\n\x0eserializedData\x18\x02 \x01(\x0c\x12(\n\x04sent\x18\x03 \x01(\x0b\x32\x1a.odcore.testdata.TimeStamp\x12,\n\x08received\x18\x04 \x01(\x0b\x32\x1a.odcore.testdata.TimeStamp')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TESTMESSAGE1 = _descriptor.Descriptor(
  name='TestMessage1',
  full_name='odcore.testdata.TestMessage1',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='a', full_name='odcore.testdata.TestMessage1.a', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=12,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=75,
)


_TESTMESSAGE2 = _descriptor.Descriptor(
  name='TestMessage2',
  full_name='odcore.testdata.TestMessage2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field1', full_name='odcore.testdata.TestMessage2.field1', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='field2', full_name='odcore.testdata.TestMessage2.field2', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=123,
)


_TESTMESSAGE3 = _descriptor.Descriptor(
  name='TestMessage3',
  full_name='odcore.testdata.TestMessage3',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field1', full_name='odcore.testdata.TestMessage3.field1', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=125,
  serialized_end=155,
)


_TESTMESSAGE4 = _descriptor.Descriptor(
  name='TestMessage4',
  full_name='odcore.testdata.TestMessage4',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field1', full_name='odcore.testdata.TestMessage4.field1', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=218,
)


_TESTMESSAGE5 = _descriptor.Descriptor(
  name='TestMessage5',
  full_name='odcore.testdata.TestMessage5',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field1', full_name='odcore.testdata.TestMessage5.field1', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='field2', full_name='odcore.testdata.TestMessage5.field2', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='field3', full_name='odcore.testdata.TestMessage5.field3', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='field4', full_name='odcore.testdata.TestMessage5.field4', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-100,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='field5', full_name='odcore.testdata.TestMessage5.field5', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=True, default_value=10000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='field6', full_name='odcore.testdata.TestMessage5.field6', index=5,
      number=6, type=17, cpp_type=1, label=1,
      has_default_value=True, default_value=-10000,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='field7', full_name='odcore.testdata.TestMessage5.field7', index=6,
      number=7, type=4, cpp_type=4, label=1,
      has_default_value=True, default_value=12345,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='field8', full_name='odcore.testdata.TestMessage5.field8', index=7,
      number=8, type=18, cpp_type=2, label=1,
      has_default_value=True, default_value=-12345,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='field9', full_name='odcore.testdata.TestMessage5.field9', index=8,
      number=9, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(-1.2345),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='field10', full_name='odcore.testdata.TestMessage5.field10', index=9,
      number=10, type=1, cpp_type=5, label=1,
      has_default_value=True, default_value=float(-10.2345),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='field11', full_name='odcore.testdata.TestMessage5.field11', index=10,
      number=11, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=_b("Hello World!").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='field12', full_name='odcore.testdata.TestMessage5.field12', index=11,
      number=12, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=221,
  serialized_end=542,
)


_TESTMESSAGE6 = _descriptor.Descriptor(
  name='TestMessage6',
  full_name='odcore.testdata.TestMessage6',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field1', full_name='odcore.testdata.TestMessage6.field1', index=0,
      number=4, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=544,
  serialized_end=578,
)


_TESTMESSAGE7 = _descriptor.Descriptor(
  name='TestMessage7',
  full_name='odcore.testdata.TestMessage7',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field1', full_name='odcore.testdata.TestMessage7.field1', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=580,
  serialized_end=614,
)


_TESTMESSAGE8ENTRY = _descriptor.Descriptor(
  name='TestMessage8Entry',
  full_name='odcore.testdata.TestMessage8Entry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='odcore.testdata.TestMessage8Entry.key', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='odcore.testdata.TestMessage8Entry.value', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=616,
  serialized_end=663,
)


_TESTMESSAGE8 = _descriptor.Descriptor(
  name='TestMessage8',
  full_name='odcore.testdata.TestMessage8',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='field1', full_name='odcore.testdata.TestMessage8.field1', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=665,
  serialized_end=731,
)


_TESTMESSAGE10 = _descriptor.Descriptor(
  name='TestMessage10',
  full_name='odcore.testdata.TestMessage10',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='myArray1', full_name='odcore.testdata.TestMessage10.myArray1', index=0,
      number=1, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
    _descriptor.FieldDescriptor(
      name='myArray2', full_name='odcore.testdata.TestMessage10.myArray2', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=_descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=733,
  serialized_end=792,
)


_TIMESTAMP = _descriptor.Descriptor(
  name='TimeStamp',
  full_name='odcore.testdata.TimeStamp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='seconds', full_name='odcore.testdata.TimeStamp.seconds', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='microseconds', full_name='odcore.testdata.TimeStamp.microseconds', index=1,
      number=2, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=794,
  serialized_end=844,
)


_CONTAINER = _descriptor.Descriptor(
  name='Container',
  full_name='odcore.testdata.Container',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dataType', full_name='odcore.testdata.Container.dataType', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='serializedData', full_name='odcore.testdata.Container.serializedData', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='sent', full_name='odcore.testdata.Container.sent', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='received', full_name='odcore.testdata.Container.received', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=847,
  serialized_end=988,
)

_TESTMESSAGE4.fields_by_name['field1'].message_type = _TESTMESSAGE1
_TESTMESSAGE5.fields_by_name['field12'].message_type = _TESTMESSAGE1
_TESTMESSAGE8.fields_by_name['field1'].message_type = _TESTMESSAGE8ENTRY
_CONTAINER.fields_by_name['sent'].message_type = _TIMESTAMP
_CONTAINER.fields_by_name['received'].message_type = _TIMESTAMP
DESCRIPTOR.message_types_by_name['TestMessage1'] = _TESTMESSAGE1
DESCRIPTOR.message_types_by_name['TestMessage2'] = _TESTMESSAGE2
DESCRIPTOR.message_types_by_name['TestMessage3'] = _TESTMESSAGE3
DESCRIPTOR.message_types_by_name['TestMessage4'] = _TESTMESSAGE4
DESCRIPTOR.message_types_by_name['TestMessage5'] = _TESTMESSAGE5
DESCRIPTOR.message_types_by_name['TestMessage6'] = _TESTMESSAGE6
DESCRIPTOR.message_types_by_name['TestMessage7'] = _TESTMESSAGE7
DESCRIPTOR.message_types_by_name['TestMessage8Entry'] = _TESTMESSAGE8ENTRY
DESCRIPTOR.message_types_by_name['TestMessage8'] = _TESTMESSAGE8
DESCRIPTOR.message_types_by_name['TestMessage10'] = _TESTMESSAGE10
DESCRIPTOR.message_types_by_name['TimeStamp'] = _TIMESTAMP
DESCRIPTOR.message_types_by_name['Container'] = _CONTAINER

TestMessage1 = _reflection.GeneratedProtocolMessageType('TestMessage1', (_message.Message,), dict(
  DESCRIPTOR = _TESTMESSAGE1,
  __module__ = 'OpenDaVINCITestData_pb2'
  # @@protoc_insertion_point(class_scope:odcore.testdata.TestMessage1)
  ))
_sym_db.RegisterMessage(TestMessage1)

TestMessage2 = _reflection.GeneratedProtocolMessageType('TestMessage2', (_message.Message,), dict(
  DESCRIPTOR = _TESTMESSAGE2,
  __module__ = 'OpenDaVINCITestData_pb2'
  # @@protoc_insertion_point(class_scope:odcore.testdata.TestMessage2)
  ))
_sym_db.RegisterMessage(TestMessage2)

TestMessage3 = _reflection.GeneratedProtocolMessageType('TestMessage3', (_message.Message,), dict(
  DESCRIPTOR = _TESTMESSAGE3,
  __module__ = 'OpenDaVINCITestData_pb2'
  # @@protoc_insertion_point(class_scope:odcore.testdata.TestMessage3)
  ))
_sym_db.RegisterMessage(TestMessage3)

TestMessage4 = _reflection.GeneratedProtocolMessageType('TestMessage4', (_message.Message,), dict(
  DESCRIPTOR = _TESTMESSAGE4,
  __module__ = 'OpenDaVINCITestData_pb2'
  # @@protoc_insertion_point(class_scope:odcore.testdata.TestMessage4)
  ))
_sym_db.RegisterMessage(TestMessage4)

TestMessage5 = _reflection.GeneratedProtocolMessageType('TestMessage5', (_message.Message,), dict(
  DESCRIPTOR = _TESTMESSAGE5,
  __module__ = 'OpenDaVINCITestData_pb2'
  # @@protoc_insertion_point(class_scope:odcore.testdata.TestMessage5)
  ))
_sym_db.RegisterMessage(TestMessage5)

TestMessage6 = _reflection.GeneratedProtocolMessageType('TestMessage6', (_message.Message,), dict(
  DESCRIPTOR = _TESTMESSAGE6,
  __module__ = 'OpenDaVINCITestData_pb2'
  # @@protoc_insertion_point(class_scope:odcore.testdata.TestMessage6)
  ))
_sym_db.RegisterMessage(TestMessage6)

TestMessage7 = _reflection.GeneratedProtocolMessageType('TestMessage7', (_message.Message,), dict(
  DESCRIPTOR = _TESTMESSAGE7,
  __module__ = 'OpenDaVINCITestData_pb2'
  # @@protoc_insertion_point(class_scope:odcore.testdata.TestMessage7)
  ))
_sym_db.RegisterMessage(TestMessage7)

TestMessage8Entry = _reflection.GeneratedProtocolMessageType('TestMessage8Entry', (_message.Message,), dict(
  DESCRIPTOR = _TESTMESSAGE8ENTRY,
  __module__ = 'OpenDaVINCITestData_pb2'
  # @@protoc_insertion_point(class_scope:odcore.testdata.TestMessage8Entry)
  ))
_sym_db.RegisterMessage(TestMessage8Entry)

TestMessage8 = _reflection.GeneratedProtocolMessageType('TestMessage8', (_message.Message,), dict(
  DESCRIPTOR = _TESTMESSAGE8,
  __module__ = 'OpenDaVINCITestData_pb2'
  # @@protoc_insertion_point(class_scope:odcore.testdata.TestMessage8)
  ))
_sym_db.RegisterMessage(TestMessage8)

TestMessage10 = _reflection.GeneratedProtocolMessageType('TestMessage10', (_message.Message,), dict(
  DESCRIPTOR = _TESTMESSAGE10,
  __module__ = 'OpenDaVINCITestData_pb2'
  # @@protoc_insertion_point(class_scope:odcore.testdata.TestMessage10)
  ))
_sym_db.RegisterMessage(TestMessage10)

TimeStamp = _reflection.GeneratedProtocolMessageType('TimeStamp', (_message.Message,), dict(
  DESCRIPTOR = _TIMESTAMP,
  __module__ = 'OpenDaVINCITestData_pb2'
  # @@protoc_insertion_point(class_scope:odcore.testdata.TimeStamp)
  ))
_sym_db.RegisterMessage(TimeStamp)

Container = _reflection.GeneratedProtocolMessageType('Container', (_message.Message,), dict(
  DESCRIPTOR = _CONTAINER,
  __module__ = 'OpenDaVINCITestData_pb2'
  # @@protoc_insertion_point(class_scope:odcore.testdata.Container)
  ))
_sym_db.RegisterMessage(Container)


_TESTMESSAGE6.fields_by_name['field1'].has_options = True
_TESTMESSAGE6.fields_by_name['field1']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_TESTMESSAGE7.fields_by_name['field1'].has_options = True
_TESTMESSAGE7.fields_by_name['field1']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_TESTMESSAGE10.fields_by_name['myArray1'].has_options = True
_TESTMESSAGE10.fields_by_name['myArray1']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
_TESTMESSAGE10.fields_by_name['myArray2'].has_options = True
_TESTMESSAGE10.fields_by_name['myArray2']._options = _descriptor._ParseOptions(descriptor_pb2.FieldOptions(), _b('\020\001'))
# @@protoc_insertion_point(module_scope)
