/*
 * generated by Xtext
 */
package org.opendavinci;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class CANDataModelRuntimeModule extends org.opendavinci.AbstractCANDataModelRuntimeModule {

}
