#!/bin/sh

Java_JAVA_EXECUTABLE=$1
ODDATASTRUCTUREGENERATOR_EXECUTABLE=$2
ODVD_FILE=$3
DESTINATION_DIR=$4

rm -fr $DESTINATION_DIR && \
     mkdir -p $DESTINATION_DIR && \
     cd $DESTINATION_DIR && \
     $Java_JAVA_EXECUTABLE -jar $ODDATASTRUCTUREGENERATOR_EXECUTABLE $ODVD_FILE
