# Test17 - Data structure library generated by CANDataStructureGenerator.
###########################################################################
# Try to find Test17 library.
# The user can specify an additional search path using the CMake variable
# TEST17_DIR
# First, search at the specific user path setting.
IF(NOT ("${TEST17_DIR}" STREQUAL ""))
    FIND_PATH(TEST17_INCLUDE_DIR test17/GeneratedHeaders_Test17.h
                 NAMES test17
                 PATHS ${TEST17_DIR}/include
                 NO_DEFAULT_PATH)
    FIND_LIBRARY(TEST17_LIBRARY
                 NAMES test17 test17-static
                 PATHS ${TEST17_DIR}/lib
                 NO_DEFAULT_PATH)
ENDIF()
IF(   ("${TEST17_INCLUDE_DIR}" STREQUAL "TEST17_INCLUDE_DIR-NOTFOUND")
   OR ("${TEST17_DIR}" STREQUAL "") )
    MESSAGE(STATUS "Trying to find Test17 in default paths.")
    # If not found, use the system's search paths.
    FIND_PATH(TEST17_INCLUDE_DIR test17/GeneratedHeaders_Test17.h
                 NAMES test17
                 PATHS /usr/include
                       /usr/local/include)
    FIND_LIBRARY(TEST17_LIBRARY
                 NAMES test17 test17-static
                 PATHS /usr/lib
                       /usr/lib64
                       /usr/local/lib
                       /usr/local/lib64)
ENDIF()
IF("${TEST17_INCLUDE_DIR}" STREQUAL "")
    MESSAGE(FATAL_ERROR "Could not find Test17 library.")
ENDIF()
###########################################################################
# Set linking libraries.
SET(TEST17_LIBRARIES ${TEST17_LIBRARY})
SET(TEST17_INCLUDE_DIRS ${TEST17_INCLUDE_DIR})
###########################################################################
INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(LibTest17 DEFAULT_MSG
                                  TEST17_LIBRARY TEST17_INCLUDE_DIR)
MARK_AS_ADVANCED(TEST17_INCLUDE_DIR TEST17_LIBRARY)
